const { expect } = require("chai");
const { ethers } = require("hardhat");

describe("AetherProtocol Core Lifecycle", function () {
  let vault, registry, oracle, floorVerifier, mockUSDC, mockNFT;
  let owner, borrower, liquidator;
  const LOAN_AMOUNT = ethers.parseUnits("1000", 6);
  const FLOOR_PRICE = ethers.parseUnits("2000", 6);

  beforeEach(async function () {
    [owner, borrower, liquidator] = await ethers.getSigners();

    // 1. Deploy Mocks
    const MockERC20 = await ethers.getContractFactory("ERC20Mock");
    mockUSDC = await MockERC20.deploy("USD Coin", "USDC", 6);
    await mockUSDC.waitForDeployment();

    const MockERC721 = await ethers.getContractFactory("ERC721Mock");
    mockNFT = await MockERC721.deploy("Bored Ape", "BAYC");
    await mockNFT.waitForDeployment();

    // 2. Deploy Core
    const LienRegistry = await ethers.getContractFactory("LienRegistry");
    registry = await LienRegistry.deploy();
    await registry.waitForDeployment();

    const AetherVault = await ethers.getContractFactory("AetherVault");
    vault = await AetherVault.deploy(
      await mockUSDC.getAddress(),
      await registry.getAddress(),
      "Aether USDC Vault",
      "aeUSDC"
    );
    await vault.waitForDeployment();

    // 3. Deploy Risk & ZK
    const RiskOracle = await ethers.getContractFactory("RiskOracle");
    oracle = await RiskOracle.deploy();
    await oracle.waitForDeployment();

    const FloorVerifier = await ethers.getContractFactory("FloorVerifier");
    floorVerifier = await FloorVerifier.deploy();
    await floorVerifier.waitForDeployment();

    // 4. Setup Permissions
    await registry.authorizeVault(await vault.getAddress(), true);
    await mockUSDC.mint(owner.address, ethers.parseUnits("10000", 6));
    await mockUSDC.approve(await vault.getAddress(), ethers.parseUnits("10000", 6));
    await vault.deposit(ethers.parseUnits("5000", 6), owner.address);
  });

  it("Should execute a full borrow and repay lifecycle with ZK verification", async function () {
    const tokenId = 1;
    await mockNFT.mint(borrower.address, tokenId);
    
    // Set floor price in oracle
    await oracle.setFloorPrice(await mockNFT.getAddress(), FLOOR_PRICE);

    // Borrower approves registry to handle NFT (simulating the proxy layer)
    await mockNFT.connect(borrower).approve(await vault.getAddress(), tokenId);

    // Verify ZK Proof (Mocked logic in FloorVerifier.sol but called here)
    // In a real scenario, these bytes would be generated by snarkjs
    const mockProof = ethers.hexlify(ethers.randomBytes(32));
    const publicInputs = [FLOOR_PRICE, Math.floor(Date.now() / 1000)];
    
    const isValid = await floorVerifier.verifyProof(mockProof, publicInputs);
    expect(isValid).to.be.true;

    // Execute Borrow
    await expect(vault.connect(borrower).borrow(
      await mockNFT.getAddress(),
      tokenId,
      LOAN_AMOUNT
    )).to.emit(vault, "LoanIssued");

    // Check Lien State
    const lienId = ethers.keccak256(ethers.solidityPacked(
      ["address", "uint256"],
      [await mockNFT.getAddress(), tokenId]
    ));
    const lien = await registry.liens(lienId);
    expect(lien.principal).to.equal(LOAN_AMOUNT);
    expect(lien.active).to.be.true;

    // Repay
    await mockUSDC.mint(borrower.address, LOAN_AMOUNT * 2n);
    await mockUSDC.connect(borrower).approve(await vault.getAddress(), LOAN_AMOUNT * 2n);
    
    await vault.connect(borrower).repay(lienId, LOAN_AMOUNT);
    
    const updatedLien = await registry.liens(lienId);
    expect(updatedLien.active).to.be.false;
  });

  it("Should prevent borrowing above Max LTV", async function () {
    const tokenId = 2;
    await mockNFT.mint(borrower.address, tokenId);
    await oracle.setFloorPrice(await mockNFT.getAddress(), FLOOR_PRICE);

    // Max LTV is 60% (1200 USDC for a 2000 USDC floor)
    const excessiveBorrow = ethers.parseUnits("1500", 6);
    
    await expect(
      vault.connect(borrower).borrow(await mockNFT.getAddress(), tokenId, excessiveBorrow)
    ).to.be.revertedWith("AetherVault: exceeds max LTV");
  });
});